name: Run bob to perform actions on the project.
inputs:
  input:
    default: .
    description: Path to the defold project.
  output:
    default: build/defold
    description: Path for the build output.
  args:
    type: string
    description: Free-form args for bob.
  action:
    required: true
    description: Action to run.
  platform:
    type: string
    description: Platform to bundle for.
  architectures:
    type: string
    description: Comma-separated list of architectures to bundle for.
  bundle_output:
    type: string
    description: Path for the bundle output.
  build_server:
    type: string
    description: Address of the cloud build server.
    required: false
  email:
    type: string
    required: false
    description: Email for cloud-builder.
  auth:
    type: string
    required: false
    description: Auth for cloud-builder.

runs:
  using: composite
  steps:
  - shell: bash
    run: |
      declare -a BOB_ARGS
      BOB_ARGS=(
        --verbose
        --root "${{ inputs.input }}"
        --output "${{ inputs.output }}"
        ${{ inputs.args }}
      )

      if [ -n "${{ inputs.build_server }}" ]; then
        BOB_ARGS+=(
          --build-server "${{ inputs.build_server }}"
        )
      fi

      if [ -n "${{ inputs.email }}" ]; then
        if [ -z "${{ inputs.auth }}" ]; then
          echo '::error title="Configuration Issue"::Both `email` and `auth` should be provided at the same time.'
        fi
        BOB_ARGS+=(
          --email "${{ inputs.email }}"
          --auth "${{ inputs.auth }}"
        )
      fi

      case "${{ inputs.action }}" in
      build)
        BOB_ARGS+=( --archive )
        ;;
      bundle)
        BOB_ARGS+=(
          --bundle-output "${{ inputs.bundle_output }}"
          --platform "${{ inputs.platform }}"
          --architectures "${{ inputs.architectures }}"
        )
        ;;
      *)
        ;;
      esac

      BOB_ARGS+=( "${{ inputs.action }}" )

      java -jar "${BOB}" "${BOB_ARGS[@]}"
