name: Run bob to perform actions on the project.
inputs:
  input:
    default: .
    description: Path to the defold project.
  output:
    default: build/defold
    description: Path for the build output.
  args:
    type: string
    description: Free-form args for bob.
  action:
    required: true
    description: Action to run.
  platform:
    type: string
    description: Platform to bundle for.
  architectures:
    type: string
    description: Comma-separated list of architectures to bundle for.
  bundle_output:
    type: string
    description: Path for the bundle output.

runs:
  using: composite
  steps:
  - shell: bash
    run: |
      declare -a BOB_ARGS
      BOB_ARGS=(
        --verbose
        --root "${{ inputs.input }}"
        --input "${{ inputs.input }}"
        --output "${{ inputs.output }}"
        ${{ inputs.args }}
      )

      case "${{ inputs.action }}" in
      build)
        BOB_ARGS+=( --archive )
        ;;
      bundle)
        BOB_ARGS+=(
          --bundle_output "${{ inputs.bundle_output }}"
          --platform "${{ inputs.platform }}"
          --architectures "${{ inputs.architectures }}"
        )
        ;;
      *)
        ;;
      esac

      BOB_ARGS+=( "${{ inputs.action }}" )

      java -jar "${BOB}" "${BOB_ARGS[@]}"
