name: Package into .tgz archive and publish artifact.
inputs:
  input:
    description: Path to the input directory.
    required: true
  output:
    description: Path to the output file.
    required: true
outputs:
  artifact_name:
    description: Name of the uploaded artifact.
    value: ${{ steps.package_tgz.outputs.artifact_name }}

runs:
  using: composite
  steps:
  - id: package_tgz
    shell: bash
    run: |
      tar -cvf "${{ inputs.output }}" -C "${{ inputs.input }}" .

      artifact_name=`basename "${{ inputs.output }}"`

      echo "artifact_name=${artifact_name}" >> "${GITHUB_ENV}"

  - uses: actions/upload-artifact@v3
    with:
      name: ${{ env.artifact_name }}
      path: ${{ inputs.output }}
