name: Package and publish artifact.
inputs:
  input:
    description: Path to the input directory.
    required: true
  output:
    description: Path to the output file.
    required: true
  project_name:
    description: Name of the defold project.
    required: true
  bundle_type:
    description: |
      Type of bundle to make. One of 'tgz', 'zip', 'dmg', 'ipa' or 'apk'.
    required: true
outputs:
  artifact_name:
    description: Name of the uploaded artifact.
    value: ${{ steps.package.outputs.artifact_name }}

runs:
  using: composite
  steps:
  - id: package
    shell: python
    env:
      INPUTS: ${{ toJSON(inputs) }}
      PYTHONPATH: ${{ github.action_path }}/..
    run: |
      import pathlib
      import shutil

      import toolkit

      @toolkit.inputs
      class Inputs:
          input: pathlib.Path
          output: pathlib.Path
          project_name: str
          bundle_type: str

      inputs = Inputs.load()

      def package_dmg(inputs) -> pathlib.Path:
          (inputs.input / 'Applications').symlink_to('/Applications')

          toolkit.check_call([
              'hdiutil', 'create',
              '-format', 'UDZO',
              '-srcfolder', inputs.input,
              '-volname', inputs.project_name,
              inputs.output,
          ])

      def package_archive(format):
          def package(inputs):
              output = shutil.make_archive(
                  inputs.output.with_suffix(''),
                  format, root_dir=inputs.input, base_dir='.')
              toolkit.debug(f'Packaged archive: {output}')

          return package

      def package_apk(inputs):
          apk = inputs.input / inputs.project_name / f'{inputs.project_name}.apk'
          inputs.output.hardlink_to(apk)

      def package_ipa(inputs):
          ipa = inputs.input / f'{inputs.project_name }.ipa'
          ipa.hardlink_to(inputs.output)

      package = {
          'tgz': package_archive('gztar'),
          'zip': package_archive('zip'),
          'dmg': package_dmg,
          'apk': package_apk,
          'ipa': package_ipa,
      }[inputs.bundle_type]

      package(inputs)
      toolkit.set_env('artifact_name', inputs.output.name)
      toolkit.set_output('artifact_name', inputs.output.name)

  - uses: actions/upload-artifact@v3
    with:
      name: ${{ env.artifact_name }}
      path: ${{ inputs.output }}
