name: Resolve the project dependencies.
inputs:
  project_path:
    default: .
    description: Path to the defold project.
  output:
    default: ./build
    description: Path for the build output.
  args:
    type: string
    description: Extra arguments for bob.
  settings:
    type: string
    required: false
    description: Comma-separated list of settings files to merge into project.

runs:
  using: composite
  steps:
  - uses: alex-ac/defold-workflows/actions/bob@master
    with:
      input: .${{ inputs.project_path }}
      output: ${{ inputs.output }}/default
      args: ${{ inputs.args }}
      settings: ${{ inputs.settings }}
      action: resolve

