name: Detect defold project name
inputs:
  project_path:
    default: .
    description: Path to the defold project
outputs:
  project_name:
    description: The name of the project from game.project file.
    value: ${{ steps.detect_project_name.outputs.project_name }}
runs:
  using: composite
  steps:
  - id: detect_project_name
    run: |
      python3 "${{ github.action_path }}/detect_project_name.py" \
          "${{ input.project_path }}"
  - run: |
      echo "DEFOLD_PROJECT_NAME=${{ steps.detect_project_name.outputs.project_name }}" >> "${GITHUB_ENV}"
