on:
  workflow_call:
    inputs:
      project_path:
        description: Path to the project in the repository.
        type: string
        default: .
      defold_version:
        type: string
        description: The engine hash or release channel to download.
        default: stable
      build_server:
        type: string
        description: The cloud build server to use.
        required: false

      bundle_x86_64_linux:
        type: boolean
        default: ${{ true }}
        description: Bundle for x86_64-linux (Linux)
      bundle_x86_64_win:
        type: boolean
        default: ${{ true }}
        description: Bundle for x86_64-win32 (Windows).
      bundle_x86_win:
        type: boolean
        default: ${{ true }}
        description: Bundle for x86-win32 (Legacy Windows).
      bundle_x86_64_mac:
        type: boolean
        default: ${{ true }}
        description: Bundle for x86_64-darwin (MacOS).
      bundle_arm64_ios:
        type: boolean
        default: ${{ true }}
        description: Bundle for x86_64-darwin (iOS).
      bundle_armv7_android:
        type: boolean
        default: ${{ true }}
        description: Bundle for armv7-android (Legacy Android).
      bundle_arm64_android:
        type: boolean
        default: ${{ true }}
        description: Bundle for arm64-android (Android).
      bundle_wasm_web:
        type: boolean
        default: ${{ true }}
        description: Bundle for wasm-web (WebAssembly).
      bundle_js_web:
        type: boolean
        default: ${{ false }}
        description: Bundle for js-web (JavaScript).

    secrets:
      email:
        required: false
        description: Email for cloud-builder.
      auth:
        required: false
        description: Auth token for cloud-builder.

jobs:
  setup_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup_matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: alex-ac/defold-workflows

    - uses: ./actions/setup_matrix
      id: setup_matrix
      with:
        bundle_x86_64_linux: ${{ inputs.bundle_x86_64_linux }}
        bundle_x86_64_win: ${{ inputs.bundle_x86_64_win }}
        bundle_x86_win: ${{ inputs.bundle_x86_win }}
        bundle_x86_64_mac: ${{ inputs.bundle_x86_64_mac }}
        bundle_arm64_ios: ${{ inputs.bundle_arm64_ios }}
        bundle_armv7_android: ${{ inputs.bundle_armv7_android }}
        bundle_arm64_android: ${{ inputs.bundle_arm64_android }}
        bundle_wasm_web: ${{ inputs.bundle_wasm_web }}
        bundle_js_web: ${{ inputs.bundle_js_web }}
  build:
    needs: setup_matrix
    strategy:
      matrix: ${{ fromJSON(needs.setup_matrix.outputs.matrix) }}

    runs-on: ${{ matrix.host_os }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: alex-ac/defold-workflows

    - uses: actions/checkout@v3
      with:
        path: ./src/

    - uses: ./actions/build
      timeout-minutes: 10
      with:
        project_path: ./src/${{ inputs.project_path }}
        output: ./build/default
        build_server: ${{ inputs.build_server }}
        email: ${{ secrets.email }}
        auth: ${{ secrets.auth }}
        platform: ${{ matrix.platform }}
        architectures: ${{ matrix.architectures }}
        bundle_type: ${{ matrix.bundle_type }}
