on:
  workflow_call:
    inputs:
      project_path:
        description: Path to the project in the repository.
        type: string
        default: .
      defold_version:
        type: string
        description: The engine hash or release channel to download.
        default: stable
      build_server:
        type: string
        description: The cloud build server to use.
        required: false
    secrets:
      email:
        required: false
        description: Email for cloud-builder.
      auth:
        required: false
        description: Auth token for cloud-builder.

jobs:
  build:
    strategy:
      matrix:
        host_os: [ 'ubuntu-latest' ]
        target_os: [ 'linux' ]
        target_arch: [ 'x86_64' ]
        architectures: [ 'x86_64-linux' ]
        bundle_type: [ 'tgz' ]

        include:
        - host_os: ubuntu-latest
          target_os: win32
          target_arch: x86_64
          architectures: x86_64-win32
          bundle_type: zip
        - host_os: ubuntu-latest
          target_os: win32
          target_arch: x86
          architectures: x86-win32
          bundle_type: zip
        - host_os: ubuntu-latest
          target_os: android
          target_arch: armv7
          architectures: arm64-android,armv7-android
          bundle_type: apk
        - host_os: ubuntu-latest
          target_os: web
          target_arch: js
          architectures: wasm-web
          bundle_type: tgz
        - host_os: macos-latest
          target_os: darwin
          target_arch: x86_64
          architectures: x86_64-darwin
          bundle_type: dmg
        - host_os: macos-latest
          target_os: darwin
          target_arch: arm64
          architectures: arm64-darwin
          bundle_type: ipa
    runs-on: ${{ matrix.host_os }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: alex-ac/defold-workflows

    - uses: actions/checkout@v3
      with:
        path: ./src/

    - uses: ./actions/build
      timeout-minutes: 10
      with:
        project_path: ./src/${{ inputs.project_path }}
        output: ./build/default
        build_server: ${{ inputs.build_server }}
        email: ${{ secrets.email }}
        auth: ${{ secrets.auth }}
        platform: ${{ matrix.target_arch }}-${{ matrix.target_os }}
        architectures: ${{ matrix.architectures }}
